spring:
  application:
    name: dispatch-solver
  profiles:
    active: dev
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml

  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: passw0rd
      config:
        namespace: dev
        group: DEFAULT_GROUP
        file-extension: yaml
        refresh-enabled: true
